# Testing compose extension for CI and local development
# Use with: docker compose -f docker-compose.yml -f docker-compose.test.yml up -d
# Adds mailcatcher for email testing and builds images locally instead of using published ones
services:
  db:
    ports:
      - "5432:5432"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  prestart:
    build:
      context: ./backend
    environment:
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
      - SMTP_TLS=false
      - EMAILS_FROM_EMAIL=noreply@example.com
    depends_on:
      db:
        condition: service_healthy
        restart: true
      mailcatcher:
        condition: service_started

  backend:
    build:
      context: ./backend
    environment:
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
      - SMTP_TLS=false
      - EMAILS_FROM_EMAIL=noreply@example.com
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
      mailcatcher:
        condition: service_started

  frontend:
    build:
      context: ./frontend

  playwright:
    build:
      context: ./frontend
      dockerfile: Dockerfile.playwright
    ipc: host
    depends_on:
      backend:
        condition: service_healthy
      mailcatcher:
        condition: service_started
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000
      - MAILCATCHER_HOST=http://mailcatcher:1080
      # For the reports when run locally
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./frontend/blob-report:/app/blob-report
      - ./frontend/test-results:/app/test-results
    ports:
      - 9323:9323
