backends:
  # Mock backend for testing and development
  mock:
    description: "Mock adapter for testing"
    language: es
    adapter:
      type: mock
      config: {}

  # Example Grocy instance 1 (using default English normalization)
  grocy1:
    description: "Production Grocy instance"
    language: es
    adapter:
      type: grocy
      config:
        base_url: "https://grocy1.example.com"
        api_key: "${GROCY1_API_KEY:-demo_api_key_1}"
        verify_ssl: true
        external_url: "https://grocy1.example.com"

# Global settings
settings:
  default_threshold: 0.8
  max_candidates: 5

# Language-specific normalizer configurations. Overrides the defaults for the specified language.
languages:
  es:
  #     # Spanish normalization configuration
  #     stopwords:
  #       - "la"
  #       - "las"
  #       - "el"
  #       - "los"
  #       - "de"
  #       - "del"
  #       - "al"
  #     expansions:
  #       "kg": "kilogramo"
  #       "gr": "gramo"
  #       "l": "litro"
  #       "ml": "mililitro"
