"""
English-specific normalization rules.
"""


# import spacy

# Common English stopwords to remove
STOPWORDS = {
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "up",
    "about",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "between",
    "among",
    "throughout",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "should",
    "could",
    "can",
    "may",
    "might",
    "must",
    "shall",
    "this",
    "that",
    "these",
    "those",
    "extra",
    "weight",
    "bulk",
    "pound",
    "ounce",
    "kilogram",
    "gram",
    "liter",
    "milliliter",
    "quality",
    "selection",
    "premium",
    "special",
    "fresh",
    "natural",
    "large",
    "medium",
    "small",
    "mini",
    "maxi",
    "container",
    "package",
    "unit",
    "piece",
    "flavor",
    "variety",
    "brand",
    "type",
    "traditional",
    "artisanal",
    "homemade",
    "home",
    "delicious",
    "tasty",
    "rich",
    "exquisite",
    "new",
    "improved",
    "renewed",
    "updated",
    "authentic",
    "genuine",
    "original",
    "classic",
    "crispy",
    "soft",
    "creamy",
    "tender",
    "intense",
    "strong",
    "light",
    "sweet",
    "salty",
    "spicy",
    "bitter",
    "hot",
    "cold",
    "warm",
    "quick",
    "easy",
    "simple",
    "practical",
    "complete",
    "whole",
    "total",
    "perfect",
    "select",
    "gourmet",
    "chef",
    "professional",
    "family",
    "house",
}

# Common English food/product abbreviations
EXPANSIONS = {
    "oz": "ounce",
    "lb": "pound",
    "lbs": "pounds",
    "pkg": "package",
    "ct": "count",
    "ea": "each",
    "dz": "dozen",
    "sm": "small",
    "md": "medium",
    "lg": "large",
    "xl": "extra large",
    "org": "organic",
    "nat": "natural",
    "ff": "fat free",
    "lf": "low fat",
    "nf": "no fat",
    "sf": "sugar free",
    "ns": "no sugar",
    "gf": "gluten free",
    "df": "dairy free",
    "veg": "vegetarian",
    "vgn": "vegan",
    "pcs": "pieces",
    "pc": "piece",
    "btl": "bottle",
    "can": "can",
    "jar": "jar",
    "box": "box",
    "bag": "bag",
    "whl": "whole",
    "conc": "concentrated",
    "past": "pasteurized",
    "refr": "refrigerated",
    "frz": "frozen",
    "envr": "environmentally",
    "sust": "sustainable",
    "rec": "recyclable",
    "w/": "with",
    "w/o": "without",
    "no": "without",
}

# heavy development, not used currently. Finish logic for es.py first.
