"""Add MatchLog and PendingQuery tables, remove Item table

Revision ID: 090498e10a94
Revises: 1a31ce608336
Create Date: 2025-09-30 23:44:48.257122

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '090498e10a94'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('normalized_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('matched_product_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('matched_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendingquery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('normalized_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('candidates', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('backend', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_table('pendingquery')
    op.drop_table('matchlog')
    # ### end Alembic commands ###
